### ISSUE TITLE
Tx failed for usertag with custom Exchange wallet

### ISSUE THREAD

**Issue by JuxxFR** [mantso/just.game-issues#20] opened 2019-12-25 17:22 UTC
Expected Behavior : user wants to purchase a tag using custom Exchange wallet

![Screenshot_20191225-094156_Chrome](https://user-images.githubusercontent.com/39766629/71448905-3ee97200-2743-11ea-968c-e3eaab2a2ea5.jpg)

Actual Behavior :  When he validate his tag, receive an error "Cannot read property 'txID' or undefined"

Steps to Reproduce the Problem
- close Tronlink
- open Chrome and login
- go to promote page
- type desired tag and validate

Specifications
Operating System: Android 8 and Deskop
Browser: Chrome
address: custom Exchange wallet : TAJTveGPbqCTDzZGk7B6FHFskEM3KejEz3 (500+ boxes)

Login Method : custom Exchange Wallet with and without Tronlink open

**Comment by cryptoknighte** [comment] 2019-12-26 23:43
Duplicate of #14 closing

**Closed as completed** 2019-12-26 23:43 UTC
